/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ra63_2014_pnrs1_rtrk_taskmanager_CalculateStatsNative */

#ifndef _Included_ra63_2014_pnrs1_rtrk_taskmanager_CalculateStatsNative
#define _Included_ra63_2014_pnrs1_rtrk_taskmanager_CalculateStatsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ra63_2014_pnrs1_rtrk_taskmanager_CalculateStatsNative
 * Method:    calculatePercentage
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_ra63_12014_pnrs1_rtrk_taskmanager_CalculateStatsNative_calculatePercentage
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
